
### .github/workflows/lint-and-format.yml

name: Lint and Format

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install black flake8 mypy
      
      - name: Check formatting with black
        run: |
          black --check src/ tests/ examples/
      
      - name: Lint with flake8
        run: |
          flake8 src/ tests/ examples/
      
      - name: Type check with mypy
        run: |
          mypy src/ --ignore-missing-imports

